### ISSUE TITLE
jquery ui not in license section of readme

### ISSUE THREAD

**Issue by BlueGreenMagick** [Arthur-Milchior/anki-resize-image#1]
Hello, I was looking through your code when I noticed you seem to be using jquery ui library, but did not in your readme's "Links, licence and credits" section, which I think was unintended.

**Comment by Arthur-Milchior** [comment]
Hi,

I thank you for letting me know. Yeah, I'm not really used to doing real programming and didn't thought about it. 
May I ask whether there was any reason for you to look at the code ? Any change you intend to make maybe ? Any missing feature ?

**Comment by BlueGreenMagick** [comment]
The addon is a really fantastic idea, but I feel that it still needs a little more polishing. I was hoping for something similar to one found in Evernote windows, where there are clear image borders, being able to change width-height ratio, etc. And if possible, an option to crop out a picture. 

So I was looking through the code to see if I could make some improvements. And maybe see if it could be incorporated it into the edit field during review addon easily. But sadly, the addon seems to be written entirely with jquery which I'm not quite familiar with.

**Comment by Arthur-Milchior** [comment]
I was not familiar with jQuery either. I had to learn it to make this add-on. More precisely, Anki itself uses jQuery, so I kept using jQuery. I should note that jQuery is compatible with plain javascript if you prefer to use JS without jQuery. 

Are you one of the people who did comment on ankiweb under the add-on ? Someone also mentioned borders.

I should not however that borders is something that can be deal with css alone. Actually, I'll do a small change. On hover, it'll show a small border, and so you know where to click. 

You can change width-height ration. But you need to go into the add-on configuration to allow it. Most beta tester tells me they prefer resizing to be proportional in general, and so I made it the default configuration. It's indicated in the readme. I don't know how to make it more clear.

**Comment by BlueGreenMagick** [comment]
My apologies, I'd only read the ankiweb description, and only skimmed through the README. And no, I haven't commented on the AnkiWeb yet, as I don't think I've got the hang of your addon yet. The different clicks are still quite confusing :)

Oh and I should also remind you that you haven't updated the license section your README yet.

**Comment by BlueGreenMagick** [comment]
Can I also ask you if I should assume that you won't be implementing the feature to the edit field during review addon if the kickstarter doesn't meet its goal?

**Comment by Arthur-Milchior** [comment]
I didn't push correctly. Right.
What do you mean by "different click" ? Normally, in default mode, there is a single click in bottom or right side.
If you add the "limit width/height" then I get how it can be confusing. Hopefully once it has border when it can be resized, it gets better

**Comment by Arthur-Milchior** [comment]
You're totally right in your assumption. That seems to be hours of work if I'm optimistic. Then I'll probably see unexpected problems and actually spend day on it. I don't care about this feature myself. If no one care enough to put some money in it (e.g. 20 people putting 5€), then I really think it's not worth it.

**Comment by Arthur-Milchior** [comment]
Last update adds a border. It's css and can be changed in the configuration
