### ISSUE TITLE
Was working a few days ago, not working now. It's as if I don't have the addon installed.

### ISSUE THREAD

**Issue by D4n22** [Arthur-Milchior/anki-resize-image#10]
The black border doesn't appear and the cursor doesn't change to the resizing icon. I'm on version 2.1.22 and tried reinstalling Anki. I also tried disabling all the other addons but didn't fix anything. Am using the default settings 
{
    "0": 0,
    "apply maximum height when not resizing": false,
    "apply maximum width when not resizing": false,
    "apply minimum height": true,
    "apply minimum width": true,
    "image-classes": [],
    "max-height": 200,
    "max-width": 200,
    "min-height": 10,
    "min-width": 10,
    "preserve ratio while resizing": "current",
    "resizable-style": "border:1px dashed black;"
}

**Comment by AnKingMed** [comment]
I just updated and I'm having the same issue.  It appears my max width when not resizing is applied, but I cannot click on the image to make it full size and then resize it as previously.

**Comment by Arthur-Milchior** [comment]
Corrected. Sorry, I forgot to add some files in the addon package.
