### ISSUE TITLE
Anyway to have images appear on the same line?

### ISSUE THREAD

**Issue by alih1029** [Arthur-Milchior/anki-resize-image#11]
https://imgur.com/1JTT3Lm

here is an example, is there a way to have the images all appear on one line?

**Comment by Arthur-Milchior** [comment]
When images are small enough, no problem.
But you can't easily force images to go on the left/right of the window. This is not related to this add-on, even without it, anki will resize images to make them fit the window

**Comment by Arthur-Milchior** [comment]
Note that when you review the image, they may well be on the same line. If you look at long lines of text, the change of line may change to adapt to the window size. That's going to be the same things with images, they are just considered as one big letter
