### ISSUE TITLE
Can't resize unless I change card type

### ISSUE THREAD

**Issue by jazzmonki** [Arthur-Milchior/anki-resize-image#14]
Hi Arthur,
I have an issue where I can't resize an image unless I first change the card type. I don't actually have to change the card type, but I do have to click on the Card Type and then re-select the existing card type. If I do that, it works. But then I have to do it again with the next image.

Using on my PC:
Version 2.1.14 (7b93e985)
Qt 5.12.1 PyQt 5.11.3

**Comment by Arthur-Milchior** [comment]
Please update anki. It's currently 2.1.23 and I won't maintain add-ons for version as old as 2.1.14
I'll note that it does not work on .14 on ankiweb
