### ISSUE TITLE
Bug with Latest Anki Beta

### ISSUE THREAD

**Issue by fa21212** [Arthur-Milchior/anki-resize-image#18]
I'm running the latest version of Resize Images in Editor on Beta 6 of Anki 2.1.24. I keep getting this error when I have Resize Images in editor enabled, but I don't get it when I disable the add-on. You have a great add-on and it would be wonderful if it were compatible with the latest Anki version. The Anki error I receive is below.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.24 (394f7c63) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-18 17:14:45
Add-ons possibly involved: ⁨Resize images in editor⁩

Error in sys.excepthook:
Traceback (most recent call last):
  File "aqt/errors.py", line 19, in excepthook
  File "aqt/errors.py", line 48, in write
UnicodeEncodeError: 'ascii' codec can't encode character '\xab' in position 357: ordinal not in range(128)

Original exception was:
Traceback (most recent call last):
  File "aqt/webview.py", line 459, in handler
  File "aqt/editor.py", line 451, in oncallback
  File "aqt/gui_hooks.py", line 1168, in __call__
  File "/Users/faisalahmad/Library/Application Support/Anki2/addons21/1103084694/__init__.py", line 67, in add_style_to_note
    UnicodeEncodeError: 'ascii' codec can't encode character '\xab' in position 23: ordinal not in range(128)

**Comment by Arthur-Milchior** [comment]
Thanks. I'll look at it

**Comment by Arthur-Milchior** [comment]
Please update

**Comment by fa21212** [comment]
It works now. Thank you!
