### ISSUE TITLE
Error with config

### ISSUE THREAD

**Issue by Serech99** [Arthur-Milchior/anki-resize-image#20]
Hey Arthur

First off. Big thanks for making this addon! It seems like a very great addition to Anki, that makes working with images a lot easier.  
I've been using Anki for a little while now. I've mostly used the basic tools and a few addons. I've decided to utilize the programs possibilities some more and have downloaded some addons, that seems really helpful. Here is a list of what I currently have installed:  
![addons_installed](https://user-images.githubusercontent.com/64206038/80106125-bd331500-8579-11ea-865d-91144a67397e.png)

The addon itself seems to be working just fine. My problem comes when I try to tinker with the settings. I get the following error message: 
![error_message](https://user-images.githubusercontent.com/64206038/80102284-d2f10c00-8572-11ea-897e-c274055f6873.png)

The message comes even when I just open the config menu and then try and click ok. Despite not having changed any value. I've also tried reinstalling, only running this add-on. Nothing seems to work. I can't find anything about it on your github or from a web search. 
Maybe its some obvious thing that's easy to solve, but I don't really have any experience with coding, so any help would be greatly appreciated :)

**Comment by Arthur-Milchior** [comment]
Thank you for filling the bug report. It was a mistake of mine. It should be corrected. Please update

**Comment by Serech99** [comment]
It works now. Thanks for the help :)
