### ISSUE TITLE
possible to stop breaking <div> ?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Arthur-Milchior/anki-resize-image#23]
Hello again!

I'm doing a project with cloze that will probably end up as an addon in a while.

This cloze system allows for gradual unclozing a bit like cloze overlapper (it is pretty much an enhanced iTraveller script) but also works with pictures. An issue for me is that inserting images with your (great addon) breaks <div> tags, causing the image to be in a newline and doesn't work with my code (it inserts the newline just after {{c1:: and before }}).

Is that necessary? I have a VERY limited understanding of anki in this regard.

ps : can you look at this issue with the addon symbol as you type ? https://github.com/jefdongus/insert-symbols-anki-addon/issues/11#issuecomment-621897320
I think your addon behaves the same way and doesn't behave normally with the undo.

PS2 : if you want to take a look at the project, you can find the current cloze template I'm using there : https://github.com/thiswillbeyourgithub/Oliver_Cloze/tree/master/current_version
(it's a basic copy of my template)

**Comment by Arthur-Milchior** [comment]
Sorry, I do not know cloze overlapper nor iTraveller script. So it does not help a lot. I'm not a fan of cloze deletion.

I do not understand which new lines you're referring too. Can you maybe find an example of field just before/after they broke; send me the html code (you can access it when you're on the field by pressing ctrl+shift+x) and a screenhot before/after it breaks. This way I may understand what is your trouble.

I do know that there is no easy undo for my add-on. You can only double click to reset it to initial size. I'm quite sorry about it, but even with your first PS, I don't see how it will help. Worst, I don't currently have time to figure this out myself.

**Comment by thiswillbeyourgithub** [comment]
Hi

For reference iTraveller script is this : https://anki.tenderapp.com/discussions/ankidesktop/16538-opening-clozes-one-a-time

~~For the undo : I'm was actually refering to undoing insertion and text insertion. If you insert an image, then text, then image, then repeatedly press ctrl+Z the sequence is not correct. And I think it is the same principle that in the issue I referenced above.~~

It looks like the undo and breaking of div are somewhat harder to reproduce than I thought. I'll repost here when I figure it out. You can close this if you want. Sorry for disturbing before double checking.

**Comment by Arthur-Milchior** [comment]
No trouble.

This add-on does not really deal with inserting image. It uses anki's usual way to insert image. It then apply the code to resize them once they are already inserted. I may imagine that it can breaks the undo function nonetheless, however I don't expect that it breaks it more than how it is already broken

**Comment by Arthur-Milchior** [comment]
@thiswillbeyourgithub 
Since you've not reposted here since May, may I assume you didn't figure out and I can cloze this bug ?

**Comment by thiswillbeyourgithub** [comment]
I adapted my way of writing cards and undoing etc so as to avoid issues. AFAIC you can close it. Thanks!
