### ISSUE TITLE
Apply maximum height not working 

### ISSUE THREAD

**Issue by Lenticulostriate** [Arthur-Milchior/anki-resize-image#28]
Please read post here:

https://www.reddit.com/r/Anki/comments/ih38bt/images_are_not_resizing/

I had to resort to CSS because the config settings were not working.

**Comment by Arthur-Milchior** [comment]
It seems to me that you misunderstood what mean "maximum height". As explained in the documentation https://github.com/Arthur-Milchior/anki-resize-image#maximum-height-or-width it only mean "maximal height in the editor". The goal is to avoid having huge images when you edit the card. It's not supposed to change anything to the card content when you are not editing it

**Comment by Lenticulostriate** [comment]
Thanks Arthur, do you know why the add-on is interfering with the actual card though? The CSS code in styling should change the image but it is not due to the add-on.

**Comment by Lenticulostriate** [comment]
Actually, it doesn't even matter. Thanks for putting up with stupid people like me, this add-on is a godsend.

**Comment by Arthur-Milchior** [comment]
Sorry, I'm pretty pretty bad with CSS and try to avoid it as much as I can. Probably fear it too much for the good of my card.
Thanks for coming to github, that's easy to answer here. No trouble
