### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by yanyu2015** [Arthur-Milchior/anki-resize-image#3]
![image](https://user-images.githubusercontent.com/11142054/75083807-8da26500-5556-11ea-9cff-4a8c7cfcb0fd.png)

![image](https://user-images.githubusercontent.com/11142054/75083899-5aaca100-5557-11ea-881e-d8828dd7151a.png)

**Comment by Arthur-Milchior** [comment]
Do you have the add-on "maximum image height in card editor" ? It seems to be a problem which is related.
Normally, installing my add-on should uninstall the add-on "maximum image height in card editor" but it seems like it failed.
If you uninstall the addon "maximum image height in card editor", restart anki and double click on the image, it should get its ususal size back. 

Or did you change the default config of the current add-on and set "apply maximum height/width when not resizing" to true ? In which case resizing is expected, and the result should not been so small in the reviewer. You can give normal size back by clicking on the image.

If I'm wrong, then I'll ask for you to let me know what add-ons you have and what anki version it is

**Comment by Arthur-Milchior** [comment]
I use an already existing library for resizing, there is no way for me currently to allow to resize by clicking left/top. Anyway, the image can't be freely moved in the field, it's considered as any text, so changing the width on the right or left side would lead to the same result

**Comment by yanyu2015** [comment]
![image](https://user-images.githubusercontent.com/11142054/75085522-38218480-5565-11ea-99fc-841540040402.png)

as you see
@Arthur-Milchior

**Comment by Arthur-Milchior** [comment]
There are answers I'm still missing: did you change the default config ? What's the anki version

I forgot one other question, did you update it today ?  The last update adds a border around image, in order to let people know where they should click to resize. Given that there is no border, it seems that the screenshot was taken either when the card could not be resized, or with an older version.

Were you able to resize the image by the way ?

**Comment by Arthur-Milchior** [comment]
Can you please tell me what HTML/warkdown does ? I don't speak the language used in https://ankiweb.net/shared/info/831016260

There are too many add-ons to check all of them manually for me. Can I ask you to disable all of them and try resize alone. If it doesn't work, I'll know I don't have to look at all add-ons and only at your os/anki version/config. Otherwise, I'll need to find which add-on creates the problem.

If the problem is due to another add-on, can you use dichotomy to find which add-on is incompatible. That is, disable only half the add-on. If it still break, disable half of the enabled add-ons. And so on until it works again. Then it means the incompatible add-on is one of the add-on disabled recently.  You can do this until you found only the very add-on creating the problem. Then I can try to make them compatible.

**Comment by yanyu2015** [comment]
my anki version is 2.1.16.Your add-on has been updated today. I have tried to disable other addons  and try resize alone.The problem still appears.
A good news is double-click works.my pictures are all pasted from clipboard,use software snippaste.Thank you~

**Comment by Arthur-Milchior** [comment]
I've never heard of snippaste. I may need to take a look at it. That still seems quite strange to me; that makes very little sens. And clearly, as a dev', I would prefer to ensure you that you won't have to double click on each image.

**Comment by yanyu2015** [comment]
it just a screenshot software
https://zh.snipaste.com/#
you can find it in windows app store.
I am confuse about anki's mechanism
if my screenshot is large,when paste in anki,it's large
it seems that when pasting pictures into anki，it has some other properties which can't been seen，should I use CTRL+SHIFT+V?

**Comment by Arthur-Milchior** [comment]
I don't use windows. There is no version for linux currently.

You can see every properties by clicking in the field and then ctrl+shift+x. It's plain HTML. 
With my add-on, you'll see some more properties indeed. They are the one needed to make images resizable. And the image size should sometime be indicated. Normally, it should not have other properties.

**Comment by yanyu2015** [comment]
I have found the reason is my original picture is large
if I modify config as follows：
{
    "0": 0,
    "apply maximum height when not resizing": true,
    "apply maximum width when not resizing": true,
    "apply minimum height when not resizing": false,
    "apply minimum width when not resizing": false,
    "max-height": "600px",
    "max-width": "600px",
    "min-height": "200px",
    "min-width": "200px",
    "preserve ratio while resizing": "current",
    "resizable-style": "border:1px dashed black;"
}
It compresses little.
![image](https://user-images.githubusercontent.com/11142054/75089070-fd811180-558f-11ea-8ce8-a1a432f3d494.png)

I have another question,if there is a way can make picture automatically/default be max large and its proportion is proper?
It can be done in MS word
I am fraind that if you can understand.I am sorry for my porr English.

**Comment by Arthur-Milchior** [comment]
I think I understand.
Set the config to
```{
"0": 0,
"apply maximum height when not resizing": false,
"apply maximum width when not resizing": false,
"apply minimum height when not resizing": false,
"apply minimum width when not resizing": true,
"max-height": "600px",
"max-width": "600px",
"min-height": "200px",
"min-width": "100%",
"preserve ratio while resizing": "original",
"resizable-style": "border:1px dashed black;"
}
```
But if you do so, you can't resize images anymore. The image is fixed to maximum size
You may need to double click on the image to give them max width

**Comment by yanyu2015** [comment]
a suggestion：
if a fixed max or min has been setted,it may be in disproportional.
if set 100%,it can’t resize images anymore.
can set 100%,and resize images by mutiple(in a way of drag its corner)?
example:
original size  :h 150px,w 300px
2          times:h 300px,w 600px
0.8       times:h 120px,w 240px

**Comment by yanyu2015** [comment]
after some trials,config as follows may worls：
{
    "0": 0,
    "apply maximum height when not resizing": true,
    "apply maximum width when not resizing": true,
    "apply minimum height when not resizing": false,
    "apply minimum width when not resizing": false,
    "max-height": "100%",
    "max-width": "100%",
    "min-height": "200px",
    "min-width": "200px",
    "preserve ratio while resizing": "current",
    "resizable-style": "border:1px dashed black;"
}

**Comment by Arthur-Milchior** [comment]
You can't both have image at maximum width and being able to resize it. So I don't actually know what you are looking for.

**Comment by yanyu2015** [comment]
You know that I set max as 100%,it just origial size,in this way,I can drag and
resize image.may be set all options false,it still can drag and resize image?

**Comment by Arthur-Milchior** [comment]
I am really sorry, but I am having too much trouble understanding what you mean. Do you think you could try asking someone speaking both your mother tongue and English or French translating. Because right now I can't answer
