### ISSUE TITLE
Does not work on ⁨2.1.38 

### ISSUE THREAD

**Issue by Bortex19** [Arthur-Milchior/anki-resize-image#32]

**Comment by ad1tyachaudhary** [comment]
This add-on is the most used add-on by me on Anki, kindly look into the issue Mr.@Arthur-Milchior

**Comment by Arthur-Milchior** [comment]
Please update and let me know if it's still broken. If so, please give more details

**Comment by Bortex19** [comment]
Fixed! 👏
________________________________
De: Arthur Milchior <notifications@github.com>
Enviado: miércoles, 30 de diciembre de 2020 13:49
Para: Arthur-Milchior/anki-resize-image <anki-resize-image@noreply.github.com>
Cc: Bortex19 <berto.lorenzo@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Arthur-Milchior/anki-resize-image] Does not work on ⁨2.1.38 (#32)


Please update and let me know if it's still broken. If so, please give more details

**Comment by Bortex19** [comment]
> Please update and let me know if it's still broken. If so, please give more details

It's fixed 🥳
Thank you, Arthur!

**Comment by AnKingMed** [comment]
Seems to have fixed it. Thanks as always Arthur!

**Comment by Arthur-Milchior** [comment]
Thanks a lot for warning me while it was in Beta, the AnKing. Was actually pretty simple, if only I had an easy way to know when thing would be simple to fix
