### ISSUE TITLE
/

### ISSUE THREAD

**Issue by GitHubWhatsup** [Arthur-Milchior/anki-resize-image#38]
/

**Comment by Arthur-Milchior** [comment]
Which file?

**Comment by GitHubWhatsup** [comment]
> Which file?

This add on is open source, right? So I want to download this add on directly from GitHub and then I will put the file in the Anki add on folder manually. I don't want to download by entering code number "1103084694". How do I know the source code of that folder is the same as you put on GitHub?

Thanks.
