### ISSUE TITLE
Image gets resized automatically to a small ineligible lump on Mac

### ISSUE THREAD

**Issue by ExtremeCoolDude** [Arthur-Milchior/anki-resize-image#4]
Steps to reproduce the issue :

1. Tile the windows or resize the main Anki window
2. Press "e" to edit card during reviews.
3. You get this : 
![image](https://user-images.githubusercontent.com/50034073/75095369-0c7db900-55bc-11ea-8f43-10e6b6b25fcc.png)

The small square on the bottom left is what is left of the image.

**Comment by ExtremeCoolDude** [comment]
Installed add-ons : 

![image](https://user-images.githubusercontent.com/50034073/75095466-1d7afa00-55bd-11ea-9d93-b51313c47194.png)

**Comment by ExtremeCoolDude** [comment]
I should also add that if you don't touch "back", the resized image automatically becomes normal after exiting the "edit cards", but if you edit something, it is saved as a tiny bump, which can be later stretched, but not to its prior glory, it is kinda disfigured, for eg: 

![image](https://user-images.githubusercontent.com/50034073/75095711-e8bc7200-55bf-11ea-9484-d9cc77426d9f.png)

Also for some strange reason, some cards are automatically exhibiting this behavior on  anki browser, but appear fine while reviewing :
 
![image](https://user-images.githubusercontent.com/50034073/75095723-14d7f300-55c0-11ea-9af4-fd97852937cc.png)

![image](https://user-images.githubusercontent.com/50034073/75095727-29b48680-55c0-11ea-97af-e5fad3bd561b.png)

**Comment by Arthur-Milchior** [comment]
Can you please update and let me know whether it works.
It may takes a few second before image get resizable.

**Comment by ExtremeCoolDude** [comment]
It seems to be working perfecto atm. Will update if anything breaks!
Tysm for quick reply and quick fix.

**Comment by Arthur-Milchior** [comment]
I honestly had no clue what did occur. Great it s repaired. Please thing about pledging on the kickstarter if you didnt already do
