### ISSUE TITLE
not working in 'add' anymore!

### ISSUE THREAD

**Issue by joeejoee98** [Arthur-Milchior/anki-resize-image#43]
i was resizing images with this add-on while adding new cards to my deck and i was able to resize them in the editor as well. now i'am only able to resize images in the editor, i need to resize them while adding a new card

Edit: after adding a card with an unresizable image in it, the image gets resizable

**Comment by Arthur-Milchior** [comment]
Corrected, I think and hope. Can you confirm please?

**Comment by joeejoee98** [comment]
It's working again! Thank you very very much for your fast response and correction!
