### ISSUE TITLE
Cannot resize image right after copy / paste

### ISSUE THREAD

**Issue by Iris3Meow** [Arthur-Milchior/anki-resize-image#5]
When I copy an image and paste it into "Add Notecard" window or in editor, the image correctly shows in the minimized size, but I cannot edit the size.
By this, I mean that when I click on the minimized picture, the picture will not become the original size.
Double clicking at this time will warp the image into weird proportions.

The workaround I have found is to copy and paste the image, click out of that specific note 1 (ex. look at another note 2), and come back to the original note 1.
When viewing a copy / pasted image for second time, the image resizer works correctly, as intended.
I don't know what may be causing the issue, as I do not have any other image resizing addons.
My config is below:

{
    "0": 0,
    "apply maximum height when not resizing": true,
    "apply maximum width when not resizing": true,
    "apply minimum height when not resizing": true,
    "apply minimum width when not resizing": true,
    "max-height": "200px",
    "max-width": "200px",
    "min-height": "200px",
    "min-width": "200px",
    "preserve ratio while resizing": "original",
    "resizable-style": "border:1px dashed black;"
}

**Comment by Arthur-Milchior** [comment]
Did you update recently ?
Did you try double clicking on the image you just copy/pasted ? Normally, it should give it its initial size back.
Can you please share with me a card you created which has the bug
On 2.1.20, you can select a note in the browser and export it alone

**Comment by Iris3Meow** [comment]
With the latest update, the initial double click makes the copy/pasted picture slightly bigger, but nowhere near original size. Here is a screenshot:

![image](https://user-images.githubusercontent.com/33403306/75270711-001a7b80-57c9-11ea-97fa-24b184053366.png)
In the Extra section, that knife picture has just been copy pasted and double clicked. You can see it just a tiny bit bigger than the schistocyte blood smear picture on the left. On the right screen, you can see what that knife picture's actual size is.
The double click right after copy/paste does not show the original size.

![image](https://user-images.githubusercontent.com/33403306/75270856-4079f980-57c9-11ea-9eef-358b4958a053.png)
This is after I viewed another note and came back. Now, when I single click on the image, the image shows the true size.

I don't know if sharing a note would do much, but here it is.
[Selected Notes.zip](https://github.com/Arthur-Milchior/anki-resize-image/files/4251205/Selected.Notes.zip)

**Comment by Iris3Meow** [comment]
I am on Anki 2.1.20, if that helps

**Comment by Arthur-Milchior** [comment]
Please update and tell me whether it works now

**Comment by Iris3Meow** [comment]
The update fixes the issue when only 1-2 picture(s) have been added.
When 3+ pictures have been added, the click to original size only works on some of the pictures.
What is interesting is that if we have picture 1 2 and 3:
At first, picture 2 might not correctly change to original size with click.
After a couple clicks, now picture 2 might work fine, but picture 3 might not work correctly.
The issue shifts around between the different pictures.

**Comment by Iris3Meow** [comment]
![image](https://user-images.githubusercontent.com/33403306/75400635-d303c100-58cd-11ea-8582-6560785f888d.png)
Here is an example.
At this moment, pictures 2 and 4 clicks to original size, while pictures 1 and 3 are unresponsive.

**Comment by Arthur-Milchior** [comment]
Are you pasting everything quickly ? Like pressing ctrl+v many time in a row ?
It takes something like 2 seconds to make image resizable.
I may imagine that pasting many time quickly breaks thing. It's not a case I've thought about

**Comment by Iris3Meow** [comment]
Ahh let me try that

**Comment by Iris3Meow** [comment]
Issue persists even when 5 seconds are taken in between each paste.

**Comment by Iris3Meow** [comment]
To be honest, it already works well. So take your time and if you can't find the issue, too bad. Just let ppl know

**Comment by Arthur-Milchior** [comment]
Found the bug. Corrected it. Please try

**Comment by Iris3Meow** [comment]
Everything looks good now.
Thank you!
