### ISSUE TITLE
It disable multi-column note editor

### ISSUE THREAD

**Issue by aPaci95** [Arthur-Milchior/anki-resize-image#7]
When i activate it, it automatically disables multi-column note editor

**Comment by Arthur-Milchior** [comment]
I know it. I will add it on readme

On 2.1.21 I ll submit a correction to HSSM, because it s the other add on which should be corrected

**Comment by Arthur-Milchior** [comment]
Readme corrected

**Comment by aPaci95** [comment]
So i should only wait until 2.1.21, or it isn't sure yet? Thank you for your help ! :)

**Comment by Arthur-Milchior** [comment]
I'm sure I won't make any correction before 21. Because they will be much more easier to make then.
I can't promise that everything will work correctly then. I still need to do the actual work

**Comment by aPaci95** [comment]
I don't want to rush you, just wanted to know if you had time to take a look at the problem; and as always, i wanted to thank you for your lifesaving work!

**Comment by Arthur-Milchior** [comment]
I did submit a change to multi column add-on https://github.com/glutanimate/frozen-fields/pull/20
I'll need to see whether HSSM accept it

**Comment by aPaci95** [comment]
Thank you very much!!!!

**Comment by Arthur-Milchior** [comment]
Normally, it's compatible with multi column now. Mostly because I also became the mainteneur of the other add-on. Can you confirm it works and can we close the bug report ?

**Comment by aPaci95** [comment]
I thing i got something wrong. I see no updates to the multi-column note editor and in fact when i try to enable it, it disables the resize image in editor addon... should i do something in particular? Am i doing something wrong?

**Comment by Arthur-Milchior** [comment]
The update was days (a week ?) ago.
I'm going to check whether I did leave anything wrong in the manifest

**Comment by Arthur-Milchior** [comment]
My fault. I did indicate to ankiweb that both add-ons were incompatible, while they are not anymore. It should work now

**Comment by aPaci95** [comment]
Still, when i try to enable one of them the other get disabled

![image](https://user-images.githubusercontent.com/25055620/79065711-b4f1f480-7cb2-11ea-9cc3-4c4c3f56e92f.png)

**Comment by Arthur-Milchior** [comment]
Which version of anki are you using ? The became compatible with version .22; i didn't realize I should have told it first

**Comment by aPaci95** [comment]
I'm using 2.1.22. I tried it on 2 different pc but still when i activate one of them, it disables the other

**Comment by aPaci95** [comment]
I deleted and re-downloaded the addon and it works now! Perfect!! Thank you

**Comment by Arthur-Milchior** [comment]
That's quite strange. Re downloading should do the same thing as updating. I don't get it. I wonder whether the update process has a bug.

FYI, hopefully, it'll also be compatible soon with Frozen Field. I sent a correction to Glutanimate and don't know when he'll look at it
