### ISSUE TITLE
important? it automatically resizes images when browsing

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Arthur-Milchior/anki-resize-image#8]
Hi,
I use the addon [Browser: Table/Editor side-by-side (horizontal split)](https://ankiweb.net/shared/info/831846358) and frequently have the browser window very very small on my screen.

I think your addon automatically resizes the image when just selecting a card in the browser, as the "in browser"-editor then pops up and make it fit. I don't know if it's an imcompatibility with the other addon or if yours does it every time in the browser but it seems a bit important to me as the scaled down images are lost and unusable :)

**Comment by Arthur-Milchior** [comment]
First, you should now that when you double click on image, they get their initial size back. So nothing is really lost. Appart from the time double clicking them.

If the image is resized due to the size of the field normally the new size is not saved. However, if you edit the content of the field, I guess that the new size will be saved with the new text. Is this the problem that you found, or is this another problem ?
I have not thought about this before, but I totally see how it could happen.
I currently have no idea how to solve it. I'll take a look at this problem later, thanks for letting me know.

**Comment by thiswillbeyourgithub** [comment]
Merci for answering so qickly!
> First, you should now that when you double click on image, they get their initial size back. So nothing is really lost. Appart from the time double clicking them.

didn't know that. They are lost when removing empty media then ?

>If the image is resized due to the size of the field normally the new size is not saved. However, if you edit the content of the field, I guess that the new size will be saved with the new text. Is this the problem that you found, or is this another problem ?

I think it's what you said. Selecting a card in the browser also selects a field by default so I would guess it could do that.

>I have not thought about this before, but I totally see how it could happen.
I currently have no idea how to solve it. 

Just an idea, maybe don't resize the image if the field has been selected but not edited (either by changing text or by manually resizing the picture, as one could want to resize the image without touching the text). That might be enough don't you think ?

I have only a very limited understanding of this so at least I tried ^^.

Thanks again for this addon btw :) Will donate on every addon you create!

**Comment by Arthur-Milchior** [comment]
Now. My add-on does not delete any image. They never get lost. Furthermore, they are supposed to have a minimal size. So that it always remain at least a small image so that you can always double click on them.

**Comment by Arthur-Milchior** [comment]
Only the first field is selected. If you only loose image in the first field, then saving the field content may be the cause of your problem. Otherwise, if it removes all images, then we must look for another reason

**Comment by thiswillbeyourgithub** [comment]
It doesn't remove images, it just resizes them. If double clicking resets the default value then there is no *permanent* loss but it can still be infuriation with image occlusion, the masks are offsetted.

I'll be carefull in the next days to see if I understand more this problem or if I overreacted. Have a nice day!

**Comment by Arthur-Milchior** [comment]
I totally see the problem.
Someone asked me to mix this add-on and image occlusion. I fear it would be far too much work, given that I don't use Image occlusion myself.
I'll try to think of a solution. But that was not my priority as far as add-on goes
